### ISSUE TITLE
hedgehog-arbitrary

### ISSUE THREAD

**Issue by svalaskevicius** [hedgehogqa/scala-hedgehog#102]
not really an issue but I couldnt find any scala-hedgehog team's email to write this to :)

I've created this library https://github.com/svalaskevicius/hedgehog-arbitrary and thought you might be interested to have a look at it - maybe also share your feedback? :)

helps with generating input for big ADTs..

Regards,
Sarunas

**Comment by charleso** [comment]
Hi Sarunas,

Firstly thank you so much for the comment/feedback. I'm sorry for the
delay, we had our first child last week so just been getting used to a
whole new and very different stage of life.

Secondly, just a little feedback. Regarding the wrapper Arbitrary class, I
don't actually think you need it. By that I mean, I don't think there's any
reason not to use implicit Gen directly. My vague assumption has always
been ScalaCheck (well Rickard) ported this directly from Haskell
QuickCheck. In Haskell the split between the Gen data type and Arbitrary
typeclass is unavoidable/necessary. In Scala, at least in 2.x, you don't
have that restriction. You can see that ScalaProps (another excellent
property testing library) has done away with
<https://github.com/scalaprops/scalaprops/blob/2eec22fae359572bf0f78e7c3dd868ab73c8f3eb/core/src/main/scala/scalaprops/Property.scala#L197>
 Arbitrary entirely
<https://github.com/scalaprops/scalaprops/search?q=arbitrary+extension%3Ascala&unscoped_q=arbitrary+extension%3Ascala>
.

Thirdly, I'm sorry for the next bit of negativity, I would never like to
discourage you or anyone else from feeling part of the Scala Hedgehog
community. I'm afraid I actually think the *lack* of implicit Gen/Arbitrary
is a feature, not a bug.

Just out of curiosity, have you seen Jacob Stanley's original talk on
integrated shrinking <https://www.youtube.com/watch?v=AIv_9T0xKEo>? It's a
great talk, and one of the many original motivations for Hedgehog was to
avoid having the Arbitrary because there have been bugs that have been
missed because of a limited/restricted implementation (see 11:31 at the
"implicit choice" section of the talk
<https://www.youtube.com/watch?v=AIv_9T0xKEo?t=691>). For example, one big
source of bugs/problems I've *personally* seen in the past was related to
Arbitrary[Int] in Haskell, which had/has the unfortunate default of being
bounded from -100 to 100
<http://hackage.haskell.org/package/QuickCheck-2.13.2/docs/src/Test.QuickCheck.Arbitrary.html#line-616>.
In some ways that often means tests will quite happily run, and give you
the illusion that you're property testing the full range of Int when you're
actually not. The question is, what is the One True Implicit Default? For
Ints the that might be obvious. but what about Double, should that include
NaN and Infinity? What about String, should that always include multi-byte
Unicode (it doesn't in Haskell either)?

I suppose implicit (ha ha) in this argument is that you shouldn't really
ever override implicits in scope, which is basically true in Haskell and is
a practice I personally follow in Scala because I believe it leads to
subtle bugs and more complicated code (again, see Jacob's talk above). I
realise I am probably in the minority for that (in Scala), and my intention
is not to convince you of the merits just now unless you want to know more.

That said, I do think there is plenty of room for more sensible/default
combinators. As well as ScalaCheck
<https://github.com/typelevel/scalacheck/blob/master/src/main/scala/org/scalacheck/Gen.scala>,
ScalaProps has also done an excellent job
<https://github.com/scalaprops/scalaprops/blob/2eec22fae359572bf0f78e7c3dd868ab73c8f3eb/gen/src/main/scala/scalaprops/Gen.scala#L278-L579>of
this. I'm definitely missing some obvious primitive combinators like the
ones you've got in your repository (ie Gen.intAll, Gen.floatAll, etc), and
they probably live in the extras package
<https://github.com/hedgehogqa/scala-hedgehog/tree/master/core/src/main/scala/hedgehog/extra>
.

Lastly, there is actually a (undocumented) Slack channel for the wider
Hedgehog project if you wanted to join (just let me know what email address
to use)? It's mostly about the Haskell version at the moment but could
easily create a new #scala channel.

Off topic, do you mind me asking how you're finding Scala Hedgehog? Using
it at work or for personal projects?

Charles

**Comment by svalaskevicius** [comment]
Thanks for the comment!

Re arbitrary vs implicit gen directly - if this was in the main hedgehog code - yes, but I chose to create this extra type to be able to provide default implementation instead of orphaned instances, and it separates what is being derived via type vs combinators - this can be easily changed though.

As for the preference of combinators vs typeclass - I see your point, and I do use gen directly in most cases, but I had a rather big expression type where handrolling a generator was a rather painful task (it literally is a gadt for math-like expression with many cases) - so being able to generate it reduced my test size by quite a lot. I'll check the video when I have a chance though :)

I also more or less anticipated this thinking and that's the main reason its not a pr to hedgehog but instead is a separate library :) 

Re slack - it's a good tool for maintainers (closed community), but maybe something like an open gitter channel would allow more people to join? also gitter is quite popular on typelevel projects so at least one scala community is already using and are familiar with it

Overall, I like hedgehog but only started playing with it on my "pet project" :) maybe what would be good for using it wider are releases with semantic versioning? (release per commit is good for snapshots but makes a bit harder for users to upgrade between versions - or rather choose which version to upgrade to)

**Comment by charleso** [comment]
@svalaskevicius Ahh, so you know about Haskell and orphan instances. That's handy. Definitely worth watching Jacob's talk then, as he also talks about the issues with the Arbitrary typeclasses in QuickCheck.

I'm curious what you mean by "handrolling a generator", did you have an example or code so I could take a look? I'm not quite following how Arbitrary helps exactly (I'm sure it does, just don't quite understand).

I'm torn about creating a Gitter channel. On the one hand it lowers the bar to signing up, but on the other it will split the (small number of) hedgehog users we currently have. We should at least create a self-signup page for the slack channel for now, but no one has gotten around to it. It's definitely not just intended for contributors though. Would you like to be added to the slack group?

I've been waiting for someone to ask about switching to semantic versioning. I realise it would be mandatory/essential for wider adoption. It's partly a chicken-egg thing, I've been waiting for more users before switching to it, but on the other hand people are less likely to use Hedgehog because it doesn't have semantic versioning. (I've created an issue to track the requirement: https://github.com/hedgehogqa/scala-hedgehog/issues/103)

Please do let me know how Hedgehog goes on your pet project, and if you have any other comment/suggestions/feedback.

**Comment by etorreborre** [comment]
> we had our first child last week

:tada: Even if this is how I learn about it, huge congratulations, enjoy life with your little baby @charleso!

**Comment by svalaskevicius** [comment]
> I'm curious what you mean by "handrolling a generator", did you have an example or code so I could take a look?

The code is not yet public, but it is simply a bunch of ADTs, and GATDs in some cases, so while not complex to create generators for them, it can be a bit tedious :) with type based derivation it's a oneliner, esp that the properties there are essentially "just free me any" (eg there are some expression rewriting rules where the output of a generated expression must be the same as of the original)

Re gitter - makes sense. For new users slack seems a high step for them to jump on though - maybe just my perception.. What about a mailing list? That shouldn't conflict with slack, even better if slack has some integrations with mailing lists.. (until there is a critical mass it may be empty though...). As for me - I don't mind, but I'm not sure if I'll have enough time to actively participate - so not sure about the value adding of me there :) if there was a public channel /mailing list I'd gladly sit in and watch, maybe post something from time to time. For now I've just been watching git commits for the project updates :) 

Thanks for the semver ticket! I think it will help the adoption. esp once it's marked as v1 :) 

This is a great project - thanks for your work making it happen!

**Comment by symbiont-eric-torreborre** [comment]
I think this is a very common problem. Type-based wiring of generators is a thing we want when we start having complex/nested datatypes instead of manually wiring those generators together (in particular when there are ADT with several variants). 

On the other hand type-based wiring is also limiting because it hard-codes many default generators together. So when we want to slightly tweak one of those generators (say generate always `Some(customer)` for a `Option[Customer]` field) then we are back to manually rewire everything. Using implicit generators in Scala can help because we can, really locally for a given test override a given generator. However in some cases this is still not enough because we sometimes need to override a generator *only* if it is used by another one! (for example generate `Some(customer)` only for an `Account` and not for an `Order`). 

In Haskell I have experimented with an approach using a `registry` to "wire" generators together: https://github.com/etorreborre/registry-hedgehog. The idea to to have a type-directed automatic wiring of generators + some helpers to create generators for ADTs (using TemplateHaskell). Then also have ways to specify that a given generator should be overridden in a specific context (for `Account` but not for `Order`). This gives a lot of flexibility for testing because you can in just one line override the generation for any part of your data type (including relationships, `Option`, `List`, `Set`,...). There are other goodies which you might want to investigate in `hedgehog-scala` like generating distinct values or cycle through all the constructors of an ADT instead of randomly picking them up.

Warning: there are drawbacks to this approach including:

 - possible high-compilation times depending on which part of the API is used
 - a new API to learn for creating generators
 - a more "dynamic" set-up for generating values which must not be abused otherwise it can be non-trivial to understand how a given value is generated (because you need to track the places where a registry has been modified)

I am planning to experiment with a similar `registry-scala` library when I get some time (because the same approach can be used for other typeclasses like Encoders/Decoders or to wire components in an application).

**Comment by svalaskevicius** [comment]
Cool, sounds like a good idea @symbiont-eric-torreborre!

One approach could be to use an hlist to carry the values in the registry, then select by type. This approach would also be compatible with the code in the link above to generate instances for adts given a registry - the only code that would need to change is to extract a gen instance from the passed registry instead of plucking it from the implicit scope :)

I imagine that as a user, I'd register some generators for strings, ints etc and it would derive the rest, as long as it's an adt and all generator dependencies are provided - one thing that might be complicated - nice error messages, but that should be solvable I'd think?

**Comment by symbiont-eric-torreborre** [comment]
My main difficulty is to have nice error messages at compile-time. At run-time we can have better messages where we show in which context a given value was trying to be built but could not (the compile time message just says that it is not possible to build it). 

The Haskell implementation does not use an HList but an untyped data structure internally to allow to switch to an "unsafe" mode if the registry becomes too large and the compile times suffer. However in the normal mode we can still guarantee that it is possible to build a given value by keeping track of all the functions inputs and all the functions outputs in 2 type-level list (and checking at compile-time that the list of inputs must be contained in the list of outputs + the type you wish to build in contained in the list of outputs. The only thing that is not currently checked is the presence of cycles).

**Comment by svalaskevicius** [comment]
Yeah I did mean compile error messages :)

a custom implicit not found message should work though on the gen extractor from an hlist registry.. Need to try to be sure though :)
